[epictalesbot]
environment=
logs_path=
metrics_path=

[telegram]
bot_token=

[openai]
api_key=

[google.cloud]
credentials_file=

[aws]
region=

[aws.credentials]
aws_access_key_id=
aws_secret_access_key=
