import json
import re
import openai
import requests
import logging
import os
import xml.etree.ElementTree as ET

from config import Config


logger = logging.getLogger(__name__)

class VideoGPT:
    _VIDEO_SUMMARY_PROMPT_FILE = "video_summary_prompt.txt"

    def __init__(self, config: Config) -> None:
        openai.api_key = config.get_open_ai_key()
        file_dir = os.path.dirname(os.path.abspath(__file__))
        file_path = os.path.join(file_dir, self._VIDEO_SUMMARY_PROMPT_FILE)
        
        with open(file_path, 'r', encoding='utf-8') as file:
            self._prompt_content = file.read()

    def _gpt_it(self, title: str, text: str) -> str:
        try:
            response = openai.chat.completions.create(
                messages=[
                    {
                        "role": "user",
                        "content": self._prompt_content + f"\nTitle: {title}\nText: {text}"
                    }
                ],
                model="gpt-4-1106-preview"    
            )

            first_choice = response.choices[0]
            message = first_choice.message

            return message.content
        except Exception as e:
            logger.error(f"Error in generating summary: {e}")
            return "Sorry, I couldn't generate the summary."

    def _get_video_info(self, video_url: str) -> dict:
        response = requests.get(video_url)
        html_content = response.text

        # Find the JSON data within the HTML
        json_pattern = r"ytInitialPlayerResponse\s*=\s*({.+?})\s*;"
        json_data = re.search(json_pattern, html_content)
        if not json_data:
            return None

        video_info = json.loads(json_data.group(1))
        return video_info

    def _extract_subtitles_url(self, video_info: dict, language_code='en') -> str:
        # Extract the caption tracks from the video info. Returns first found track and None if not found.
        def find_track(caption_tracks, condition):
            return next((track for track in caption_tracks if condition(track)), None)

        caption_tracks = video_info.get('captions', {}).get('playerCaptionsTracklistRenderer', {}).get('captionTracks')
        if not caption_tracks:
            logger.error('No caption tracks found.')
            return None

        # Search for the specified language code
        result = find_track(caption_tracks, lambda track: track['languageCode'] == language_code)
        if result:
            return result['baseUrl']

        # Fallback to autogenerated subtitles in the specified language
        logger.warning(f'No subtitles found for language {language_code}. Falling back to autogenerated, looking for "a.{language_code}"')
        result = find_track(caption_tracks, lambda track: track['languageCode'].startswith('a.' + language_code))
        if result:
            return result['baseUrl']

        # Fallback to any autogenerated subtitles
        logger.warning(f'No autogenerated subtitles found for language {language_code}. Falling back to any autogenerated, looking for "a."')
        result = find_track(caption_tracks, lambda track: track['languageCode'].startswith('a.'))
        if result:
            return result['baseUrl']

        logger.error('Cannot find any suitable subtitles.')
        return None

    def _download_subtitles(self, subtitles_url: str) -> str:
        response = requests.get(subtitles_url)
        return response.text
    
    def _convert_xml_to_text(self, xml_data):
        root = ET.fromstring(xml_data)
        
        # Convert to text format
        subtitles_text = ""
        for child in root:
            start_time = child.attrib.get('start')
            text = child.text.replace("\n", " ")  # Replace newline characters with spaces
            subtitles_text += f"{start_time}\n{text}\n\n"
        
        return subtitles_text.strip()

    def summarize(self, video_url: str) -> str:
        video_info = self._get_video_info(video_url)

        if not video_info:
            logger.error(f'Cannot process URL {video_url}, video info is empty')
            return None

        subtitles_url = self._extract_subtitles_url(video_info)
        xml_subtitles = self._download_subtitles(subtitles_url)
        text_subtitles = self._convert_xml_to_text(xml_subtitles)

        return self._gpt_it(video_info['videoDetails']['title'], text_subtitles)
