AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create a DynamoDB table for ChatSettings'

Parameters:
  Stage:
    Type: String
    Default: beta
    Description: Deployment stage name

Resources:
  ChatSettingsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub "${Stage}-ChatSettings"
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: chat_id
          AttributeType: N
      KeySchema:
        - AttributeName: chat_id
          KeyType: HASH

  Records:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub "${Stage}-Records"
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: update_id
          AttributeType: N
      KeySchema:
        - AttributeName: update_id
          KeyType: HASH